### ISSUE TITLE
Image of Developers not displaying in Contact Section.

### ISSUE THREAD

**Issue by ranjal007** [threefreespirited/Jssconnect#1]
![image](https://user-images.githubusercontent.com/55893326/107855278-4c7e2180-6e47-11eb-9561-dbec5aacd86a.png)

**Comment by aniketlodh** [comment]
Hi,
I would like to work on this issue. Can I get the original long image URLs of the images?

**Comment by supzi-del** [comment]
Hey, the img src links might be wrong, please share correct source.

**Comment by sukhpreet-singh1** [comment]
@ranjal007 can you please assign me this issue?

**Comment by AMAN123956** [comment]
It will be shared once the gssoc event starts

**Comment by sukhpreet-singh1** [comment]
ok i will wait

**Comment by AMAN123956** [comment]
It has been resolved in our updated version
