### ISSUE TITLE
Refactor APP.js

### ISSUE THREAD

**Issue by subhadeepCh** [threefreespirited/Jssconnect#10]
The app.js needs to be refactored for proper scaling of the application
Please assign me this task -- GSSOC'21

**Comment by subhadeepCh** [comment]
@harshit9270 Please assign me this task

**Comment by AMAN123956** [comment]
@subhadeepCh  U can work on this issue

**Comment by subhadeepCh** [comment]
@AMAN123956 Thanks for assigning this issue to me

**Comment by subhadeepCh** [comment]
@AMAN123956 @harshit9270 Hey ,can you please add **Gssoc tag** to this issue

**Comment by harshit9270** [comment]
Hey @subhadeepCh,
Any updates?

**Comment by AlacritousCreature** [comment]
Hey @AMAN123956 @me-harshit! I would like to do this issue if it isn't done by the currently assigned one. I am a GSSOC'21 Participant.

**Comment by aniketlodh** [comment]
Hello @me-harshit @AMAN123956 @heysujal, since the assigned contributor is not responding, Can you please assign the issue to me? I can work on it. I'm a GSSOC participant.

**Comment by heysujal** [comment]
@AlacritousCreature I have assigned you the issue.

**Comment by AlacritousCreature** [comment]
@heysujal am extremely thankful to you for assigning me this issue, however, my cllg mid sem exams are going on in this week. I tried to install and make it but am ending with some errors or Google OAuth configuration and its not running te project locally without fixing those . Sorry but, I request to you please unassign me this issue. I will continue to work on this repo from next week.

**Comment by heysujal** [comment]
@aniketlodh Go Ahead.

**Comment by aniketlodh** [comment]
![Screenshot from 2021-03-21 19-49-47](https://user-images.githubusercontent.com/55927827/111908352-ea848d80-8a7e-11eb-97fd-053100629c7e.png)
I'm getting this error on running the application. Can anyone please help?

**Comment by guptapranav4299** [comment]
@AMAN123956 please assign this issue to me

**Comment by harshit9270** [comment]
@guptapranav4299 ,
Go ahead.
