### ISSUE TITLE
New user authentication not working.

### ISSUE THREAD

**Issue by Rimpi246** [threefreespirited/Jssconnect#12]
New user registration is not working.Would like to work on this as a part of GSSOC'21

**Comment by sanjeev-kumar-nsut** [comment]
it will not work at this  stage also, they are not giving user data for privacy

**Comment by AMAN123956** [comment]
@Rimpi246  it will not work as due to privacy and keeping our users data secure we hav

**Comment by AMAN123956** [comment]
@Rimpi246 d u have created ur app in Google search console as no such issue is coming otherwise share the screenshot of the issue untill then I am closing this issue
