### ISSUE TITLE
Add a favicon.

### ISSUE THREAD

**Issue by padmajabhol** [threefreespirited/Jssconnect#14]
I want to add a favicon to this website that could match its logo.

**Comment by heysujal** [comment]
@padmajabhol  Go Ahead

**Comment by Aanchal116** [comment]
Hii , 
I would like to work on this issue as a part of GSSOC'21. I've hands-on practice in web development and also a mentorship experience. Please assign this task to me if possible.

**Comment by padmajabhol** [comment]
> @padmajabhol Go Ahead

![Screenshot (14)](https://user-images.githubusercontent.com/75530516/110588423-017fd180-819b-11eb-90e0-97d114a85e46.png)
I cant load the live server, can you help me out as per why this is happening?

**Comment by DhrutikPatel** [comment]
> > @padmajabhol Go Ahead
> 
> ![Screenshot (14)](https://user-images.githubusercontent.com/75530516/110588423-017fd180-819b-11eb-90e0-97d114a85e46.png)
> I cant load the live server, can you help me out as per why this is happening?

@padmajabhol 
use command **node app** instead of **npm start**
it will load live server

**Comment by padmajabhol** [comment]
> @padmajabhol  Go Ahead

![IMG_20210310_120443_896.jpg](https://user-images.githubusercontent.com/75530516/110587139-40148c80-8199-11eb-9a43-dbf17e0ead5d.jpg) I can't run the server still not working

**Comment by DhrutikPatel** [comment]
> > @padmajabhol  Go Ahead
> 
> ![IMG_20210310_120443_896.jpg](https://user-images.githubusercontent.com/75530516/110587139-40148c80-8199-11eb-9a43-dbf17e0ead5d.jpg) I can't run the server still not working

Don't use npm start command 
use **node app** command to run live server on localhost

**Comment by harshit9270** [comment]
Hey @padmajabhol ,
Any updates or I shall assign this to anyone other.

**Comment by padmajabhol** [comment]
> Hey @padmajabhol ,
> Any updates or I shall assign this to anyone other.

I ll do it within an hour.

**Comment by harshit9270** [comment]
Wrong destination to add favicon html code.
And way too much time for this work.
