### ISSUE TITLE
Unhandled error for empty database

### ISSUE THREAD

**Issue by subhadeepCh** [threefreespirited/Jssconnect#16]
<img width="589" alt="33" src="https://user-images.githubusercontent.com/63468060/110455937-00916600-80ef-11eb-9d98-2c934acb5c7d.PNG">
Since the database is initially empty, therefore this error pops up, just need to handle this error,
@harshit9270 @AMAN123956 Please add **GSSOC tag** to this issue if you find this relevant, so that i can create a pr

**Comment by srisatya12** [comment]
I want to contribute to this issue. Please assign me this task as a part of GSSoC'21

**Comment by subhadeepCh** [comment]
@srisatya1197 Thankyou for showing interest , but i have already started working on this issue, 
@harshit9270  Please add **GSSOC tag** so that pr can be made

**Comment by srisatya12** [comment]
@subhadeepCh  ok

**Comment by harshit9270** [comment]
The number of lines of code changed are exponentially greater than any improvement.
I am unable to detect any changes or updates.
Either you reconsider your PR or I shall close this issue.
