### ISSUE TITLE
Add animation #GGSOC'21

### ISSUE THREAD

**Issue by Kritikaagra** [threefreespirited/Jssconnect#17]
Hey...
I am a GGSOC'21 participant and want to add animation to your repo for make a better experience for users.

Plz assign this to me

**Comment by AMAN123956** [comment]
@Kritikaagra  u can work on this issue deadline 12 March

**Comment by Kritikaagra** [comment]
@AMAN123956  Thqq so much...plz add GGSOC'21 label too

**Comment by nikhilgupta2001** [comment]
Hey...
I am a GGSOC'21 participant and want to work on this.Plz assign this to me

**Comment by Kritikaagra** [comment]
@AMAN123956  
I am not able to work on this... please assign this to @nikhilgupta2001  
sorry for the inconvenience

**Comment by AMAN123956** [comment]
@nikhilgupta2001 do u want to work on this issue

**Comment by nikhilgupta2001** [comment]
yah i would like to work please assign it to me

**Comment by harshit9270** [comment]
Hey @nikhilgupta2001 ,
Any updates?

**Comment by pragati-kumar** [comment]
@me-harshit I'm a GSSOC'21 participant. I would like to contribute to this issue and can get started ASAP. Could you assign this to me?

**Comment by harshit9270** [comment]
Are you still interested @pragati-kumar?

**Comment by pragati-kumar** [comment]
> Are you still interested @pragati-kumar?

Yes, sir. Thank you so much!

**Comment by harshit9270** [comment]
Any updates @pragati-kumar?
