### ISSUE TITLE
Restructuring Views

### ISSUE THREAD

**Issue by Vishal1003** [threefreespirited/Jssconnect#18]
I can see that the views folder contains duplicate html files which is already being rendered as ejs files. So it is better to move them in public folder/or a separate sub folder (static) to avoid confusions.  Further it is better to add a few dev dependencies (like nodemon etc.) for better development env.
Can I work on this? (as a part of GSSOC'21).
@AMAN123956

**Comment by Vishal1003** [comment]
@heysujal can you assign this to me so that I can work on it.? (if possible add a gssoc label)

**Comment by harshit9270** [comment]
Hey  @Vishal1003 
Remove the duplicate html files instead of moving them.
Also nodemon is already a dependency for development.
