### ISSUE TITLE
Loading CSS files properly

### ISSUE THREAD

**Issue by Vishal1003** [threefreespirited/Jssconnect#19]
@harshit9270 @heysujal  @AMAN123956  CSS files are not working on register page (probably they are broken). I'm attaching the image for reference. Kindly assign me the task to link these properly. (as a part of GSSOC'21).

![image](https://user-images.githubusercontent.com/44357051/110490465-59282980-8116-11eb-8596-5711327a686d.png)

**Comment by harshit9270** [comment]
removed the register option as google automatically adjusts to login/signup according to database.
Register page is no more required. You must look upto other issues.
