### ISSUE TITLE
New UI design for blog preview needed with proper typography

### ISSUE THREAD

**Issue by AMAN123956** [threefreespirited/Jssconnect#2]

**Comment by iamkrati22** [comment]
Hey, I would like to work on this issue as a part of gssoc'21. Can you assign it to me?

**Comment by AMAN123956** [comment]
> Hey, I would like to work on this issue as a part of gssoc'21. Can you assign it to me?

Wait for gssoc event to start I will share more details with you about how you can work on this issue

**Comment by sanjeev-kumar-nsut** [comment]
Hello sir,
I am interested in working on this issue, 
can you decsribe it in more details as you told earlier

**Comment by AMAN123956** [comment]
@iamkrati22  and @sanjeev-kumar-nsut  u both can work on this issue once done our team will see whose stuff seems good

**Comment by AMAN123956** [comment]
Keep a note that we want a like and comment button at the end of blog so design the page keeping this thing in mind

**Comment by sanjeev-kumar-nsut** [comment]
ok sir

**Comment by srk224** [comment]
Hey . I would like to work on this . I have some experience with UI/UX design.
Can you please share some more details

**Comment by AMAN123956** [comment]
@srk224  u can also work on this issue as it is a designing issue so we are assigning it to multiple persons at a time deadline to submit your work is 12 march

**Comment by Naman-12911** [comment]
Hello sir , I want solve this issue please assign me this issue under GSSOC

**Comment by AMAN123956** [comment]
@Naman-12911  u can also work on this issue deadline to submit your work is 12 march

**Comment by srk224** [comment]
I Have designed a new blog page contrasting with the older theme of the website , so that it can go well with other pages and not look different.
Here is my design:- 
![Web 1920 – 2](https://user-images.githubusercontent.com/63584405/110748197-630c7280-8265-11eb-9c69-37dbfb21eb6c.png)
![Web 1920 – 1](https://user-images.githubusercontent.com/63584405/110748204-64d63600-8265-11eb-8366-a3d19b71aa26.png)

Let me know if it is good or not? 
..or if there are any changes! I would be really happy to entertain

**Comment by sanjeev-kumar-nsut** [comment]
hello @srk224,
please contact me, my WhatsApp number is 9968704350

**Comment by AMAN123956** [comment]
> I Have designed a new blog page contrasting with the older theme of the website , so that it can go well with other pages and not look different.
> Here is my design:-
> ![Web 1920 – 2](https://user-images.githubusercontent.com/63584405/110748197-630c7280-8265-11eb-9c69-37dbfb21eb6c.png)
> ![Web 1920 – 1](https://user-images.githubusercontent.com/63584405/110748204-64d63600-8265-11eb-8366-a3d19b71aa26.png)
> 
> Let me know if it is good or not?
> ..or if there are any changes! I would be really happy to entertain

@srk224 looks great to me let me discuss with my team about this design and then I will be updating you about few changes that seems to me 
But overall great work looks cool to me

**Comment by srk224** [comment]
> > I Have designed a new blog page contrasting with the older theme of the website , so that it can go well with other pages and not look different.
> > Here is my design:-
> > ![Web 1920 – 2](https://user-images.githubusercontent.com/63584405/110748197-630c7280-8265-11eb-9c69-37dbfb21eb6c.png)
> > ![Web 1920 – 1](https://user-images.githubusercontent.com/63584405/110748204-64d63600-8265-11eb-8366-a3d19b71aa26.png)
> > Let me know if it is good or not?
> > ..or if there are any changes! I would be really happy to entertain
> 
> @srk224 looks great to me let me discuss with my team about this design and then I will be updating you about few changes that seems to me
> But overall great work looks cool to me

Thanks a lot !! Let me know the changes after the discussion

**Comment by srk224** [comment]
@AMAN123956
Thanks alot!!
Let me know the changes after the discussion

**Comment by AMAN123956** [comment]
@srk224  make a pr so that we can see your changes

**Comment by srk224** [comment]
I havent actually made the changes in the code for this blog post as I am not that good in react ! I just designed the UI part of it on adobe xd! but if you want me to do it ! I am already learning react , I can speed up my pace and do the code changes in some days!

**Comment by heysujal** [comment]
@srk224  This project is not made using React. It uses javascript.

**Comment by srk224** [comment]
I am facing this error while starting the server!
![2021-03-13](https://user-images.githubusercontent.com/63584405/111028230-5af63380-841b-11eb-913d-a37c08f5df3d.png)
can anyone help me resolve it?

**Comment by harshit9270** [comment]
@iamkrati22 ,
Since you were unable to code what you prototyped, this issue has been resoved.
BTW nice design work.
