### ISSUE TITLE
fix auth SignUp Error!! 

### ISSUE THREAD

**Issue by bhubesh757** [threefreespirited/Jssconnect#20]

**Comment by heysujal** [comment]
Provide details of issue in brief. You can attach screenshots and videos to demonstrate where the issue is actually.

**Comment by bhubesh757** [comment]
https://user-images.githubusercontent.com/55022929/110564451-dc776880-8172-11eb-9dc3-cb34c5063c02.mp4

**Comment by bhubesh757** [comment]
> Provide details of issue in brief. You can attach screenshots and videos to demonstrate where the issue is actually.

Its not invalid , its valid it redirects to localhost page , authentication error

**Comment by harshit9270** [comment]
>  vokoscreenNG-2021-03-10_07-26-03.mp4

@bhubesh757 Since this project is under development mode, we have adjusted the redirect URL for authentication to localhost for working on local devices.
Once this event gets over, we'll change the URL.
