### ISSUE TITLE
Section for college events

### ISSUE THREAD

**Issue by Rimpi246** [threefreespirited/Jssconnect#23]
I would like to add one section for getting information about upcoming events like hackathons, ideathons, conferences,coding contests,etc. 
Please `/assign` this issue  to me as a part of GSSOC'21

**Comment by heysujal** [comment]
@Rimpi246 Go Ahead.

**Comment by Rimpi246** [comment]
Okay

**Comment by AMAN123956** [comment]
@Rimpi246 u haven't provided any update about the work

**Comment by AMAN123956** [comment]
I will be closing this issue by tomorrow if no updates received
