### ISSUE TITLE
Add section of ofcampus opportunities 

### ISSUE THREAD

**Issue by Rimpi246** [threefreespirited/Jssconnect#24]
I would like to add a seperate section for ofcampus opportunities like internships,placements,scholarships,etc. which most students are not aware of.
Please `/assign` this issue to me as a part of GSSOC'21

**Comment by harshit9270** [comment]
@Rimpi246 
Go ahead with this and we'll later on go through with your work.

**Comment by Rimpi246** [comment]
Okay.

**Comment by SananditaDas** [comment]
I would like to work on this issue as a part of GSSOC'21. @me-harshit Please assign me this issue.
We can also keep the users updated with upcoming hackathons(similar to D2C). Also ask them to signup to our newsletter for regular updates.

**Comment by Rimpi246** [comment]
Hello @SananditaDas, I am actually working on this and hackathons issue is being raised in #23 and I am assigned that. But I think the newsletter sign up you should create it as a new issue.

**Comment by AMAN123956** [comment]
@Rimpi246 are u working on this issue

**Comment by Rimpi246** [comment]
Ya.. I am working on it
