### ISSUE TITLE
Like Button on Blogs not working.

### ISSUE THREAD

**Issue by Sristi27** [threefreespirited/Jssconnect#28]
The like buttons on the blog is not working!I would like to enable its functionality.
Could you assign this issue to me?

**Comment by AMAN123956** [comment]
@Sristi27 we haven't made it functioning yet we are working on the design of this page but you can work on implementing this functionality few things that u should keep in mind while working on this functionality
1.Only users that are authenticated can like the blog
2.Only one like per user should be there a user who has liked the post previously shouldn't be able to like it after that 
I am assigning this task to you so within a week give me an update about it.

**Comment by AMAN123956** [comment]
@Sristi27 are u working on this issue

**Comment by Sristi27** [comment]
Actually,my semester examinations are going on..So I am taking some time.Hope you understand and I hope to finish with it soon!

**Comment by guptapranav4299** [comment]
@AMAN123956 I would like to work on this issue under gssoc21

**Comment by yashmita** [comment]
@AMAN123956 I can work on this issue. Kindly assign it to me.

**Comment by harshit9270** [comment]
Hey @guptapranav4299 , @yashmita ,
I am waiting for response from @Sristi27. If she refuses or is unable to finish, then I shall assign this to you.  :)

**Comment by Sristi27** [comment]
> Hey @guptapranav4299 , @yashmita ,
> I am waiting for response from @Sristi27. If she refuses or is unable to finish, then I shall assign this to you. :)



![Screenshot 2021-03-24 at 5 23 01 PM](https://user-images.githubusercontent.com/53037053/112306327-b51db100-8cc5-11eb-9dcc-ed0aacedcb3c.png)



Can you help me with this error?

**Comment by harshit9270** [comment]
Hey @Sristi27,
Since I cannot give you the access to the original database, you should either create a mongo DB cluster or edit/comment the code accordingly to avoid database conflicts.

**Comment by harshit9270** [comment]
Resolved the issue
