### ISSUE TITLE
Image link broken in readme.md

### ISSUE THREAD

**Issue by satcasm** [threefreespirited/Jssconnect#3]
Hi, the image link in the readme.md seems to be broken. It's source is defined as `<img src="1.png" style="margin-top:30px;" alt="image">` but I couldn't find any ``1.png`` file in the images folder.

Screenshot for reference:
![image](https://user-images.githubusercontent.com/56315878/109398290-fee2d800-7961-11eb-8d79-734d8129ef54.png)

**Comment by AMAN123956** [comment]
Yeh you can do so by taking screenshot of home page of our website and uploading it with name 1.png

**Comment by satcasm** [comment]
Should I wait till 8th march ? As on that day GSSOC' 21 coding period starts or should I start now?
Thanks.

**Comment by AMAN123956** [comment]
Wait for the task to be assigned by mentors of gssoc

**Comment by satcasm** [comment]
@AMAN123956 , I was wondering if I can start the work and you merge my PR after 8th?

**Comment by sanjeev-kumar-nsut** [comment]
hello guys,
i also want to contribute here, 
lets make a group/team in which we can learn from each other 
interested people can mail me to : sulodha2002@gmail.com

**Comment by sanjeev-kumar-nsut** [comment]
Hello guys,
There is an  syntax error in this code ( in views/header.ejs)
PLZ reply or contact me if you can correct as this error is in many places in this project
[
[error.docx](https://github.com/threefreespirited/Jssconnect/files/6060764/error.docx)
](url)

**Comment by heysujal** [comment]
wait till 8th March

**Comment by satcasm** [comment]
Closing the issue as it is fixed.
