### ISSUE TITLE
Redesign blog page as well as footer

### ISSUE THREAD

**Issue by nandini2110** [threefreespirited/Jssconnect#30]
- This feature request is regarding the design of the Blog page and footer section. I think I can improvise on its design and styling
-  I would like to work on this issue as a part of gssoc'21.

<img width="936" alt="gss2" src="https://user-images.githubusercontent.com/51056716/110640992-78d35680-81d7-11eb-9e89-2cbc1da2469b.PNG">

<img width="947" alt="gssoc1" src="https://user-images.githubusercontent.com/51056716/110639217-72dc7600-81d5-11eb-9fb5-0c5c90942b9e.PNG">
*

-

**Comment by AMAN123956** [comment]
This issue is already been created refer to #2
