### ISSUE TITLE
Logo is not consistent 

### ISSUE THREAD

**Issue by prajjwalarora** [threefreespirited/Jssconnect#31]
## **Describe the bug**

On the home, page the logo has an icon and the text is in the center but in other parts, the text is bottom aligned.

## **Possible solution**

This can be fixed with minor changes in the Style sheet.

**Please assign this issue to me. I want to work on this under GSSOC21.

## **Screenshots**
![Screenshot (405)](https://user-images.githubusercontent.com/57281080/110686989-06c63600-8206-11eb-830b-0aa8e016e8ed.png)
![Screenshot (403)](https://user-images.githubusercontent.com/57281080/110686994-088ff980-8206-11eb-96a5-4269c339c6a0.png)
![Screenshot (404)](https://user-images.githubusercontent.com/57281080/110686996-09289000-8206-11eb-8e13-50665aa89911.png)

**Comment by anshulsharma123** [comment]
I want to work on this issue

**Comment by prajjwalarora** [comment]
I want to work on this issue. please assign me under GSSOC21.

**Comment by AMAN123956** [comment]
@prajjwalarora  u can work on this issue

**Comment by harshit9270** [comment]
Your PR is corrupting app.js , You just added 4 lines of useful code and it disturbs app.js.

**Comment by prajjwalarora** [comment]
@me-harshit hey there is no change in app.js. i only commented out one console.log in app.js. change was in header.ejs. Please look again.
