### ISSUE TITLE
Restructuring whole code. 

### ISSUE THREAD

**Issue by sanjeev-kumar-nsut** [threefreespirited/Jssconnect#32]
## Proposal
I want to re-structure the whole code
(A clear and concise description of what the proposal is.)

As there is a lot of code in app.js for example - mongoose models , schemas, routes  **all  in one place**
I want to work on this and make a different file for all for example,
There will be a separate location for all mongoose models,
different file for routes.
additional java script and css file will be on public folder.
By doing  these things , file like app.js will look **concise and small as well as user friendly**. 

Then any user can easily understand each part of code. 
he/she need not to search all models and files in app.js , he just go in models file and look in all models

**Comment by sanjeev-kumar-nsut** [comment]
Please assign me this under GSSOC' 21

**Comment by harshit9270** [comment]
Go ahead.

**Comment by sanjeev-kumar-nsut** [comment]
Hello @me-harshit ,
I had created models and routes file,
now app.js file length is of 313 line (before it was of 990 lines).
I am not able to create separate public file for extra css and html file present in views file because in discord I had asked you about need of html files but no reply came from any mentor and project admin,
Also there is my different github account linked to GSSOC '21 , so I request you to assign this issue to that ID and merge the PR if you fined it correct .
Thanks , I am enjoying to work with your project.

**Comment by sanjeev-kumar-sky** [comment]
This is my account which was linked to GSSOC'21
please consider this

**Comment by AMAN123956** [comment]
There is no need of html files actually in previous version we were not
using ejs so there were html files and but currently u can delete thes html
files as these are of no use

**Comment by sanjeev-kumar-nsut** [comment]
Please add gssoc 21 label

**Comment by harshit9270** [comment]
@sanjeev-kumar-sky ,
are you working on this?

**Comment by sanjeev-kumar-nsut** [comment]
i had completed this
but as my other account is not assigned (by which i had pushed changes) it is showing issues
plz assign this to sanjeev-kumar-sky

**Comment by harshit9270** [comment]
@sanjeev-kumar-nsut,
Maybe this will help.

**Comment by sanjeev-kumar-nsut** [comment]
the pull request is also closed
plz open it
