### ISSUE TITLE
hover effects are not smooth for buttons and links

### ISSUE THREAD

**Issue by anshulsharma123** [threefreespirited/Jssconnect#33]
Hello admins 
                    On the home page the hover effect of all buttons and links are too fast I would like to add some style effects to make them smooth please assign this work to under gssoc21 
 2) The color of hover effect in navbar links is black which is not visible in dark mode so I would like to change this also

**Comment by AMAN123956** [comment]
@anshulsharma123  go ahead

**Comment by anshulsharma123** [comment]
@AMAN123956  add gssoc21 tag and assign this to me

**Comment by harshit9270** [comment]
@anshulsharma123 ,
Are you working on this issue?
If you are, then let me know. I shall add gssoc tags then.

**Comment by anshulsharma123** [comment]
@me-harshit from past one week my CLG exams are going on so I am  not getting time to work on this issue and my exams will end on 10th April so better you assign this issue to some other peoples
