### ISSUE TITLE
[GSSOC'21] joincommunity.ejs not rendered properly

### ISSUE THREAD

**Issue by GuptaTanisha** [threefreespirited/Jssconnect#34]
- Join community not rendered properly
-
![screenshot (6)](https://user-images.githubusercontent.com/64624412/110854153-8a515700-82da-11eb-826d-c24663aaf305.jpg)

**Comment by Zeph-T** [comment]
The route is not using res.render to render the ejs file...Assign this to me under GSSOC'21

**Comment by AMAN123956** [comment]
We are working on this issue already
