### ISSUE TITLE
Would like to organize the app.js file by creating separate file for models and controller.

### ISSUE THREAD

**Issue by udaymittal7** [threefreespirited/Jssconnect#37]
## Proposal
app.js file is too big, so I would like to reorganize by creating different files for models of user, first year resources, second year resources. Also, I would like to create different files for controller functions of different routes.
I am a participant of GSSOC'21, so please let me know if this is a valid proposal and add the relevant tags.

**Comment by sanjeev-kumar-nsut** [comment]
hello @udaymittal7,
it look nice that you are also working in this issue, 
but i had already raised this issue 2 day ago,
see issue #32 under GSSOC' 21

**Comment by harshit9270** [comment]
Hey @sanjeev-kumar-nsut 
Have a look at issue #32 , that is almost the same.
