### ISSUE TITLE
Image links broken in blogs

### ISSUE THREAD

**Issue by satcasm** [threefreespirited/Jssconnect#4]
2 blogs in page https://jssconnect-beta.herokuapp.com/blogs have broken image link.

Screenshot for reference:
![image](https://user-images.githubusercontent.com/56315878/109398654-2e92df80-7964-11eb-9147-ec43a261b749.png)

**Comment by AMAN123956** [comment]
We are using unaplash api for images so when no images come from API then it shows in above ways if you can fix this issue then u can try.

**Comment by vkassingh** [comment]
Do we have a discord server for jssconnect ?

**Comment by heysujal** [comment]
No , we don't have one at this time.

**Comment by vkassingh** [comment]
> No , we don't have one at this time.

can the admins please create one. I think that would be helpful for further discussions/ brainstorming etc

**Comment by AMAN123956** [comment]
> > No , we don't have one at this time.
> 
> can the admins please create one. I think that would be helpful for further discussions/ brainstorming etc

Link for Discord Server of JSSCONNECT
https://discord.gg/72VBTkPGfn

**Comment by satcasm** [comment]
Closing the issue as it is fixed.
