### ISSUE TITLE
Responsive Resources Section 

### ISSUE THREAD

**Issue by ibhavikamalhotra** [threefreespirited/Jssconnect#41]
## **Describe the bug**

- Resources section is not responsive.

## **Possible solution**

- Making it fully responsive for all devices.

## **Screenshots**

![bug](https://user-images.githubusercontent.com/67636581/111023132-3e4b0300-83fd-11eb-923f-27101982fd96.JPG)

- Kindly assign me this issue and add the required GSSOC'21 labels to it.

**Comment by ritesh1731** [comment]
I would like to contribute to this issue under GSSOC21. Can you please assign it to me?

**Comment by AMAN123956** [comment]
@ibhavikamalhotra u can work on this issue

**Comment by harshit9270** [comment]
Any updates @ibhavikamalhotra ,
Are you working on this issue?

**Comment by harshit9270** [comment]
@ritesh1731 ,
Are you still interested to contribute to this issue?
