### ISSUE TITLE
Restructuring the Resources page

### ISSUE THREAD

**Issue by SananditaDas** [threefreespirited/Jssconnect#44]
The resources page can be made more flexible by applying **multiple filters** based on year, subject, book name, etc. to get the best possible results. Because, subject 'A' may not be taught in the 'N'th year in all colleges - so the search results cannot resort on only 1 filter.

**Comment by SananditaDas** [comment]
Please assign me this issue under GSSOC'21.

**Comment by harshit9270** [comment]
Yeah @SananditaDas ,
this was a feature in earlier version of website.
If you wish to work on this issue, then let me know. I will assign this to you under gssoc21.

**Comment by SananditaDas** [comment]
> Yeah @SananditaDas ,
> this was a feature in earlier version of website.
> If you wish to work on this issue, then let me know. I will assign this to you under gssoc21.

Yes, I am willing to work on this issue..

**Comment by harshit9270** [comment]
@SananditaDas,
You may go ahead with this.

**Comment by harshit9270** [comment]
Hey @SananditaDas,
Any updates? :)

**Comment by SananditaDas** [comment]
> Hey @SananditaDas,
> Any updates? :)

Just started working

**Comment by subhangi2731** [comment]
@harshit9270 there is no pr made please assign me this one
