### ISSUE TITLE
Create Code of Conduct

### ISSUE THREAD

**Issue by muthuannamalai12** [threefreespirited/Jssconnect#47]
I would like to add a code of conduct file as code of conduct is a necessary file which the contributors need to follow so that everyone follows a decorum.

**Comment by muthuannamalai12** [comment]
I would love to work on this issue as a part of Girl Script Summer Of Code. Kindly assign it to me.

**Comment by harshit9270** [comment]
Hey @muthuannamalai12,
Are you still interested in working on this issue?

**Comment by muthuannamalai12** [comment]
> Hey @muthuannamalai12,
> Are you still interested in working on this issue?

Yes I am interested to work on this issue.

**Comment by ANSHIKA1806** [comment]
@me-harshit @shivasinghal2000 @Surajv311 
Hello sir/mam,  I am interested to work on this issue, please assign this task to me . I would love to contribute in your organization.

**Comment by shivasinghal2000** [comment]
@ANSHIKA1806  You can work on this issue

**Comment by ANSHIKA1806** [comment]
@shivasinghal2000 
 Hello mam, You didn't assigned this issue to me how can i work on it.
 please assign this to me. Thank you.

**Comment by muthuannamalai12** [comment]
@shivasinghal2000 Can you assign it to me as I have opened this issue

**Comment by shivasinghal2000** [comment]
Sorry @ANSHIKA1806  I can't assign it to you since @muthuannamalai12 created this issue

**Comment by muthuannamalai12** [comment]
@shivasinghal2000 Can you please add the Gssoc label and level label??
