### ISSUE TITLE
Responsiveness of landing page for small screen

### ISSUE THREAD

**Issue by AMAN123956** [threefreespirited/Jssconnect#5]

**Comment by akashbwj** [comment]
I want to work on this issue as a part of GSSOC'21

**Comment by AMAN123956** [comment]
> I want to work on this issue as a part of GSSOC'21

@akashbwj  Wait for the gsssoc event to start

**Comment by Ankita297** [comment]
I want to work on this under GSSOC '21 . Please assign it to me.

**Comment by heysujal** [comment]
@Ankita297  Wait for the event to start

**Comment by akashbwj** [comment]
I want to work on this issue as a part of GSSOC'21

**Comment by AMAN123956** [comment]
@akashbwj  u can work on this issue

**Comment by harshit9270** [comment]
@Ankita297 , @akashbwj 
Are you guys working on this issue?

**Comment by Aanchal116** [comment]
Hii , 
I would like to work on this issue as a part of GSSOC'21. I've hands-on practice in web development and also a mentorship experience. Please assign this task to me if possible.

**Comment by akashbwj** [comment]
@me-harshit Yes i am :)

**Comment by chandramanipandey** [comment]
If this issue is still open and under Gssoc 21 label i would like to contribute to it @me-harshit

**Comment by AMAN123956** [comment]
Are u guys working on this issue

**Comment by akashbwj** [comment]
@AMAN123956 Yes sir! Due to offline classes and assignments its taking a little longer but i will try to complete it till or before monday! @me-harshit Thank You for assigning it to me! :D

**Comment by Ankita297** [comment]
Can i work on this ?
