### ISSUE TITLE
Adding a chatbot - gssoc'21

### ISSUE THREAD

**Issue by krishna-y2000** [threefreespirited/Jssconnect#50]
## **Is your feature request related to a problem? Please describe.**

- I would like to make a chatbot for this website . A chatbot wll help the person to find the required url in a very fast way and give answer to all the problems of user.

## **Describe the solution you'd like**

- I would include all conversation like blogs, routing to  ebooks , routing to community page , contact us and all other details.

Add the appropriate level to this issue.Please assign me this issue as part of GSSOC'21.

**Comment by Upasana1216** [comment]
I would like to work on this. Please assign this to me

**Comment by harshit9270** [comment]
Hey @Upasana1216 ,
You may go ahead with this.
Either you share any prototype of what you shall be implementing earlier or we shall consider reviewing your PR.

**Comment by harshit9270** [comment]
@Upasana1216 ,
Are you working on this?

**Comment by harshit9270** [comment]
Hey @Upasana1216,
If you still do not reply till tomorrow, I shall assign this to someone else.

**Comment by CMELAKKIA** [comment]
@harshit9270  I would like to work on this issue. Please assign this to me

**Comment by harshit9270** [comment]
@CMELAKKIA,
you may go ahead.
