### ISSUE TITLE
Considering Dockerizing the Project

### ISSUE THREAD

**Issue by jain-rishabh-21** [threefreespirited/Jssconnect#52]
## **Is your feature request related to a problem? Please describe.**

- Setting up docker to simplify the ease of use for the developers
- SO that they need not worry about setting up the env and start working straight away.
- 
## **Describe the solution you'd like**

- A clear and concise description of what you want to happen.

**Comment by jain-rishabh-21** [comment]
If found useful, can be assigned to me:
Discord: krackerzzz#4371

**Comment by AMAN123956** [comment]
@jain-rishabh-21 u can work on this issue

**Comment by harshit9270** [comment]
Any updates @jain-rishabh-21 ?

**Comment by jain-rishabh-21** [comment]
I was having trouble setting up the project! I posted it in the official group as will as pinged the mentors, but got no response @me-harshit

**Comment by harshit9270** [comment]
@jain-rishabh-21 ,
What was the issue you were facing? Is it resolved now?

**Comment by harshit9270** [comment]
@jain-rishabh-21,
It seems you are no longer interested in working on this issue. Is it?

**Comment by subhangi2731** [comment]
@harshit9270 please assign me this issue I want to work on this
