### ISSUE TITLE
navigation button to go from bottom to top

### ISSUE THREAD

**Issue by sushant1824** [threefreespirited/Jssconnect#54]
we can create one navigation button as after scrolling down to page if any user want to go directly up to page so he can just go up by clicking on that button .
that button will be user friendly ,just by clicking on that button the user can go to top of the page so that this will make user easily navigate from bottom to top .

**Comment by harshit9270** [comment]
Hey @sushant1824 
Any updates?

**Comment by sushant1824** [comment]
just working on it i was bit busy i will do it till tomorrow

**Comment by sushant1824** [comment]
<img width="960" alt="4" src="https://user-images.githubusercontent.com/62093325/112174607-8d264300-8c1c-11eb-804f-1aaea7979b90.png">

the button has been added i will pr it

**Comment by sushant1824** [comment]
@me-harshit

**Comment by harshit9270** [comment]
@sushant1824 ,
It seems that you were working on an older version of Jssconnect.
Get your repo updated and then pr it.

**Comment by sushant1824** [comment]
sir in which html file i have to make changes can u please elaborate . i
worked this on index.html

**Comment by harshit9270** [comment]
@sushant1824 , 
This project no more involves pure HTML, we use EJS instead, you need to copy your navigation button code and add to index,ejs file.
