### ISSUE TITLE
Update README file

### ISSUE THREAD

**Issue by ANSHIKA1806** [threefreespirited/Jssconnect#55]
@me-harshit @shivasinghal2000 @Surajv311 
README is the first file one should read when starting a new project. It's a set of useful information about a project, and a kind of manual. A README text file appears in many various places and refers not only to programming. So i want to make your README file more meaningful and more easier to understand the whole project.

**Comment by ANSHIKA1806** [comment]
@me-harshit @shivasinghal2000 @Surajv311
please assign this task to me .
Thank you.

**Comment by Surajv311** [comment]
go ahead @ANSHIKA1806

**Comment by ANSHIKA1806** [comment]
@Surajv311 
This issue is not assigned to me yet. Please assign it to me so that I can start working on it.
