### ISSUE TITLE
Google authentication is not working properly 

### ISSUE THREAD

**Issue by chiragasawa** [threefreespirited/Jssconnect#56]
## **Describe the bug**
@abhay27chauhan @shivasinghal2000 @me-harshit @akashbwj @heysujal 
Google authentication is not working properly .

## **Possible solution**
There is some issue in passport strategy.
## **Screenshots**

- If applicable, add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/43067874/112729458-2f626580-8f52-11eb-8fb2-1072a8459f79.png)

I would like to contribute to this issue under GSSOC21. Can you please assign it to me?

**Comment by shivasinghal2000** [comment]
go ahead @chiragasawa

**Comment by chiragasawa** [comment]
Please assign it to me.

**Comment by chiragasawa** [comment]
the issue is now fixed and tested. @shivasinghal2000  please merge my pull request.
