### ISSUE TITLE
working with mongoose means working with promises

### ISSUE THREAD

**Issue by abhay27chauhan** [threefreespirited/Jssconnect#58]
**Is your feature request related to a problem? Please describe.** 
if you are working with mongoose, means you are working with promises. So, you need to handle promise. This is an easy fix but good for long term. 

**Describe the solution you'd like** 
I suggest instead of this:

  ```
mongoose.connect(MONGODB_URI, {
    useNewUrlParser: true,
    useUnifiedTopology: true,
  });
```

You should do this:

        mongoose
          .connect(mongoURI, {
            useNewUrlParser: true,
            useUnifiedTopology: true, 
            useCreateIndex: true,
            useFindAndModify: false,
          })
          .then(() => {
            console.log('Connected to mongo db');
          })
          .catch((err) => {
            console.log("Couldn't connect to mongo db, err: ", err);
          });

**Comment by abhay27chauhan** [comment]
please let me know if this is a valid proposal

**Comment by harshit9270** [comment]
Valid point @ abhaychauhan.
Go Ahead.
