### ISSUE TITLE
Callback URL uses localhost

### ISSUE THREAD

**Issue by arnabsen1729** [threefreespirited/Jssconnect#6]
https://github.com/threefreespirited/Jssconnect/blob/2b90813a4fcbeaaefa4e94bb3a3338145da3b13f/app.js#L82

The URL mentioned here should be using the deployed url not `localhost:3000`

**Comment by AMAN123956** [comment]
@arnabsen1729  we are in the production stage that's why we haven't changed URL moreover u must read our readme before contribution as we have mentioned to not use sign in our sign up during development as no need to use it

**Comment by arnabsen1729** [comment]
Thanks, @AMAN123956 for the clarification. I think you meant **development** stage. 

As a viewer, the first thing I would do is to hop into the site that is linked and test out the features. So, I assumed it was a small typo and hence mentioned it in the issue. Also, I would advise to mention this thing not in the last line (it is literally the last line of README) rather somewhere at the top, in bold where the link is provided, that will avoid future misunderstandings. 

Looking forward to contribute :raised_hands:.

**Comment by AMAN123956** [comment]
Yeh I meant development and thanks for the suggestions will surely consider your points next time. Looking forward to adding new and innovative things to JSSConnect with you.
