### ISSUE TITLE
Development Server is not running!

### ISSUE THREAD

**Issue by asmitsirohi** [threefreespirited/Jssconnect#60]
Whenever user forked this repository and tries to run in local machine with command "npm start" then it shows "npm ERR! missing script: start".

To solve this issue, there should be some changes in package.json file.

![image](https://user-images.githubusercontent.com/63240102/113084553-d289d800-91fb-11eb-8caf-52b18f63f64d.png)

**Comment by asmitsirohi** [comment]
please assign this issue to me under GSSOC'21

**Comment by harshit9270** [comment]
@asmitsirohi 
Go ahead
