### ISSUE TITLE
Jssconnect is not running in local machine!

### ISSUE THREAD

**Issue by asmitsirohi** [threefreespirited/Jssconnect#64]
## **Describe the bug**
- When I start the deployment server using command "npm start" then it starts and makes connection with MongoDB.
- Here is screenshot,

![image](https://user-images.githubusercontent.com/63240102/113237117-e1d45880-92c3-11eb-96dc-44b7035ab7cb.png)

- But, when I run it on browser then it shows some errors.

![image](https://user-images.githubusercontent.com/63240102/113237297-34157980-92c4-11eb-9977-dc9c5650f9b4.png)

## **Possible solution**

- I think, This error occurred because application tries to read some data from database that is not present.

**Comment by chiragasawa** [comment]
@shivasinghal2000  assign to me. please i can work on this.

**Comment by shivasinghal2000** [comment]
@asmitsirohi would you like to work on this issue? Or should I assign it to @chiragasawa ?

**Comment by asmitsirohi** [comment]
@shivasinghal2000 mam, I want to work on this issue.

**Comment by shivasinghal2000** [comment]
If you won't be able to resolve this issue till 10 April, I will assign it to @chiragasawa
