### ISSUE TITLE
Change redirect url on google cloud.

### ISSUE THREAD

**Issue by chiragasawa** [threefreespirited/Jssconnect#65]
## **Describe the bug**

- Please change the redirect url in google cloud oauth is not set properly it is showing error on live heroku deployed website.

![image](https://user-images.githubusercontent.com/43067874/113280943-968d6a80-9302-11eb-90ef-61c6849a8471.png)

## **Possible solution**

change the redirect url to  this `http://jssconnect.herokuapp.com/auth/google/home` on google cloud.

## **Screenshots**

![image](https://user-images.githubusercontent.com/43067874/113283952-8ecfc500-9306-11eb-8d40-d329d736f1ac.png)
-       make as same in google cloud -> api -> credential

**Comment by bhardwajdisha** [comment]
Please assign this task to me

**Comment by hardikshah197** [comment]
May I take up this issue if no one is working on it? @chiragasawa ?

**Comment by keshavgbpecdelhi** [comment]
@chiragasawa @hardikshah197 @bhardwajdisha 
Hope we can do it soon.
