### ISSUE TITLE
Like and comment funtion is not working in blog section.

### ISSUE THREAD

**Issue by chiragasawa** [threefreespirited/Jssconnect#66]
## **Is your feature request related to a problem? Please describe.**

- Like and comment function is not working in blog section.
![image](https://user-images.githubusercontent.com/43067874/113284461-4a90f480-9307-11eb-9809-cee391978e91.png)

## **Describe the solution you'd like**

- I can work on this please assign it to me

**Comment by harshit9270** [comment]
Hey @chiragasawa,
This issue was already being worked upon. It's almost about to complete.
