### ISSUE TITLE
Links in the readme to open in a new tab 

### ISSUE THREAD

**Issue by akshay1027** [threefreespirited/Jssconnect#68]
## **Is your feature request related to a problem? Please describe.**
Links in the readme to open in a new tab so that it is easier for the user to navigate to GitHub codebase.

**Comment by harshit9270** [comment]
Go ahead

**Comment by harshit9270** [comment]
@akshay1027,
Is the code too big to implement? You're taking way more time than you should be.

**Comment by akshay1027** [comment]
sorry sir! I found out that we cant do this on Github! I tried but it's not possible @harshit9270 i ! here is the link to that: mojombo/github-flavored-markdown#28
so i will close this. Sorry sir for the inconvience.
