### ISSUE TITLE
Navbar Enhancement

### ISSUE THREAD

**Issue by Sristi27** [threefreespirited/Jssconnect#69]
## Proposal

(A clear and concise description of what the proposal is.)

![Screenshot 2021-04-06 at 1 20 28 AM](https://user-images.githubusercontent.com/53037053/113619340-777e3800-9676-11eb-895e-ebeca0ecd175.png)

The navbar signin/signup button can be enhanced.Like the outline can be removed to provide a better view.

**Comment by harshit9270** [comment]
I guess there is no need for removing the border, it looks alright. :)
