### ISSUE TITLE
add contributing.md

### ISSUE THREAD

**Issue by khareyash05** [threefreespirited/Jssconnect#70]
Hi I would like to create a file contributing.md and add the following -
Difference between GIT and GITHUB
How to clone,fork repository
How to create a branch and then use git push to push to repo
Create a PR
Squash commits in a single issue into one
Updating the forked and local repo as the updations are made in the upstream

**Comment by harshit9270** [comment]
@khareyash05 ,
You may go ahead.

**Comment by khareyash05** [comment]
@harshit9270 Created a PR Have a look #71

**Comment by harshit9270** [comment]
Merged and resolved :)
