### ISSUE TITLE
Improve Footer

### ISSUE THREAD

**Issue by akshay1027** [threefreespirited/Jssconnect#73]
## **Is your feature request related to a problem? Please describe.**
1)Find us
2)Call us
3)Mail us
4)Website logo
5)What this website is about
6)Follow us
-Instagram link with logo
-LinkedIn link with logo
-Twitter link with logo
-etc
7)Useful links
-Home
-Services
-About Us
-Contact Us etc
8)Subscribe
-Email address
9)Copyrights
10) All the above with responsive UI

**Comment by akshay1027** [comment]
I would like to work on this @harshit9270

**Comment by harshit9270** [comment]
You may go ahead @akshay1027.

**Comment by harshit9270** [comment]
@akshay1027,
Any updates?

**Comment by akshay1027** [comment]
Sorry! Am having End sem exams, wasnot able to do till yesterday, give me some time, I will try to finish it tough am new to ejs!

**Comment by srishtij2000** [comment]
Can I work on this issue?

**Comment by harshit9270** [comment]
Yeah sure! @srishtij2000

**Comment by AbhipsaGuru1012** [comment]
@harshit9270 if this issue is open I would like to work on it

**Comment by srishtij2000** [comment]
Can I work on this issue?

**Comment by srishtij2000** [comment]
I have been working on this issue and I will update it Saturday (day after tomorrow)
