### ISSUE TITLE
I want to add no.of forks, stars, issues and other in readme file.

### ISSUE THREAD

**Issue by srisatya12** [threefreespirited/Jssconnect#74]
I want to add no.of forks, stars, issues and other in readme file.
Example:
![ss5](https://user-images.githubusercontent.com/78905067/115119383-ba6cd380-9fc5-11eb-9d89-1ea70379f3e0.png)
I want to work on this . Please assign me this issue @AMAN123956 .

**Comment by harshit9270** [comment]
Merged the PR.
