### ISSUE TITLE
REAL TIME CHAT BETWEEN USERS

### ISSUE THREAD

**Issue by sanjeev-kumar-sky** [threefreespirited/Jssconnect#75]
## Wanted to add real time messaging feature

you can look about this feature in my website :
[THE BORING COLLEGE](https://theboringcollege.herokuapp.com/students)
![image](https://user-images.githubusercontent.com/60292558/115345645-b65ed280-a1cc-11eb-840c-36d09afc4391.png)

**Comment by sanjeev-kumar-sky** [comment]
Please assign me this under GSSOC 21
and this is my request to jssconnect team to please merge request as soon as possible
because you take a long time to merge and during that time so many changes are occurred to code.

**Comment by harshit9270** [comment]
Hey @sanjeev-kumar-sky,
We shall merge it as soon as it gets requested. You need to work on the UI and designing of the chat section or I shall assign the issue of design after your PR gets merged.
