### ISSUE TITLE
ADD the Light Dark mode Functionality

### ISSUE THREAD

**Issue by K-jais** [threefreespirited/Jssconnect#77]
I can Add Light Dark Mode to all of the pages which adds another feature to this website and which just gives two choices to the user as whats its preferable UI is either light or dark.

**Comment by K-jais** [comment]
@harshit9270

**Comment by harshit9270** [comment]
Ya sure! You may go ahead.

**Comment by chazuttu** [comment]
I am GSSOC'21 Participant. Please assign this issue to me and review my PR for this issue. Thank you

**Comment by harshit9270** [comment]
https://github.com/threefreespirited/Jssconnect/pull/81#issuecomment-841644883
Have a look @chazuttu .
