### ISSUE TITLE
Add a welcome bot 

### ISSUE THREAD

**Issue by Ankita297** [threefreespirited/Jssconnect#78]
## **Is your feature request related to a problem? Please describe.**

A github action to greet contributor on opening his/her first PR or first issue .

## **Describe the solution you'd like**

- A clear and concise description of what you want to happen.
![New issue · Issue #1 · Ankita297_Story - Google Chrome 22-04-2021 00_53_11](https://user-images.githubusercontent.com/67833077/115980721-72911200-a5ac-11eb-8b34-0b50bbf6376e.png)

**Comment by Ankita297** [comment]
can i work on this @harshit9270 @heysujal @AMAN123956 ?

**Comment by harshit9270** [comment]
You may go ahead.
