### ISSUE TITLE
Adding top-button

### ISSUE THREAD

**Issue by SamikshaSankar** [threefreespirited/Jssconnect#83]
## **Is your feature request related to a problem? Please describe.**

No

## **Describe the solution you'd like**

When user can scroll down by using top-button they can go to home section.

please assign this task to me

**Comment by harshit9270** [comment]
You may go ahead @SamikshaSankar.

**Comment by SamikshaSankar** [comment]
Sure..I am confused
1) In which .ejs file I have to code ?
2) same for css also ?

**Comment by harshit9270** [comment]
maybe you should look for index.ejs and index.css @SamikshaSankar

**Comment by SamikshaSankar** [comment]
@harshit9270 please help me I am unable to start this project on local server...getting this type of error
![2021-05-27 (20)](https://user-images.githubusercontent.com/52104082/119823372-5b7a7280-bf12-11eb-82c5-f6a880448f4c.png)

**Comment by ria-19** [comment]
Is this still open? I would like to contribute to this project.

**Comment by AMAN123956** [comment]
> Is this still open? I would like to contribute to this project.

@ria-19 Yeh this is still open if u want to work on this issue let us know so that we can assign this to you

**Comment by ria-19** [comment]
Yes, sure
