### ISSUE TITLE
Favicon should be present

### ISSUE THREAD

**Issue by SUCHITRAGIRI** [threefreespirited/Jssconnect#84]
## **Is your feature request related to a problem? Please describe.**
When I was exploring the project I noticed that there is no favicon, but it is quite decent project and I think favicon should be there!

## **Describe the solution you'd like**
![Screenshot (183)](https://user-images.githubusercontent.com/60110218/118962811-69188100-b983-11eb-8de5-1acd23a42492.png)
I want to add favicon so that it looks so great and professional @abhay27chauhan @chiragasawa @shivasinghal2000 @akashbwj assign me this issue so that i can work on that issue:)
Thanks!

**Comment by harshit9270** [comment]
Go ahead @SUCHITRAGIRI .

**Comment by SUCHITRAGIRI** [comment]
![Screenshot (200)](https://user-images.githubusercontent.com/60110218/119224300-681a5780-bb1b-11eb-85ae-8dbc2af69e5a.png)
Hey,  @harshit9270 @AMAN123956 @abhay27chauhan  can anyone let me know how can I fix this:(
