### ISSUE TITLE
misleading DOCs

### ISSUE THREAD

**Issue by SUCHITRAGIRI** [threefreespirited/Jssconnect#85]
## **Describe the bug**

![Screenshot (185)](https://user-images.githubusercontent.com/60110218/119122319-07701980-ba4c-11eb-8784-e1d21b9f2c25.png)

Here, it should be not like this 
` git clone https://github.com/ <your user-name> /threefreespirited/jssconnect.git`
1st we have to fork the repo then we can clone it but here it included the main repo in URL which is not possible and so, instead of this it should be like this -
` git clone https://github.com/ <your user-name> /jssconnect.git`
## **Possible solution**

I can update the docs in such a manner, so that beginner can understand it properly and will not mislead. Kindly assign me this issue @harshit9270 @abhay27chauhan @chiragasawa @shivasinghal2000.

## **Screenshots**
![Screenshot (189)](https://user-images.githubusercontent.com/60110218/119124532-659dfc00-ba4e-11eb-9d85-2539697b6652.png)
Also, no such file/folder is present in the project dir!

**Comment by AMAN123956** [comment]
U can work on this

**Comment by SUCHITRAGIRI** [comment]
But please assign me this issue didn't assign yet:(
@AMAN123956
