### ISSUE TITLE
issue and pr templates

### ISSUE THREAD

**Issue by Sloth-Panda** [threefreespirited/Jssconnect#9]
would like to add them as part of gssoc'21

**Comment by Sloth-Panda** [comment]
@heysujal @AMAN123956  can I work on this?

**Comment by harshit9270** [comment]
@Sloth-Panda 
I don't really understand what you want to state. Will you please explain?

**Comment by Sloth-Panda** [comment]
@harshit9270 hey, issue template explains an issue completely, the type of issue it's checklists and all that it follows similarly pr template too states about pr with its description and the set of checklists that it follows

**Comment by Sloth-Panda** [comment]
@harshit9270 @heysujal can you please add gssoc'21 and other required tags to this issue.
