### ISSUE TITLE
CSS Bug : Missing alignment for Guest box

### ISSUE THREAD

**Issue by mani200307** [threefreespirited/Jssconnect#90]
## **Describe the bug**

The guest box is not correctly padded or border is not removed. Also, On clicking the guest box, the padding is not fully filled.

## **Possible solution**

Possible solution could be adding padding to the image to fix the box. Or, removing the border outline for the Guest box.

## **Screenshots**

![image](https://github.com/threefreespirited/Jssconnect/assets/89850065/fbdc76fa-92a2-45e7-acd9-f25cdb35ba9c)

**Comment by mani200307** [comment]
Could you please assign me this issue?

**Comment by AMAN123956** [comment]
@mani200307 you can work on this issue
